//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JULI_IS.Resources.Pozadavky {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Filter {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Filter() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JULI_IS.Resources.Pozadavky.Filter", typeof(Filter).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Celková cena.
        /// </summary>
        public static string CelkovaCena {
            get {
                return ResourceManager.GetString("CelkovaCena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum.
        /// </summary>
        public static string Datum {
            get {
                return ResourceManager.GetString("Datum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum Do:.
        /// </summary>
        public static string DatumDo {
            get {
                return ResourceManager.GetString("DatumDo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum Od:.
        /// </summary>
        public static string DatumOd {
            get {
                return ResourceManager.GetString("DatumOd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodavatel.
        /// </summary>
        public static string Dodavatel {
            get {
                return ResourceManager.GetString("Dodavatel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtr Datum.
        /// </summary>
        public static string FilterDatum {
            get {
                return ResourceManager.GetString("FilterDatum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtr Dodavatel.
        /// </summary>
        public static string FilterDodavatel {
            get {
                return ResourceManager.GetString("FilterDodavatel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtr KST.
        /// </summary>
        public static string FilterKST {
            get {
                return ResourceManager.GetString("FilterKST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtr obsah položky.
        /// </summary>
        public static string FilterPolozkaObsah {
            get {
                return ResourceManager.GetString("FilterPolozkaObsah", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtr Požadavek.
        /// </summary>
        public static string FilterPozadavek {
            get {
                return ResourceManager.GetString("FilterPozadavek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset filtrů.
        /// </summary>
        public static string FilterReset {
            get {
                return ResourceManager.GetString("FilterReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtr Založil.
        /// </summary>
        public static string FilterZalozil {
            get {
                return ResourceManager.GetString("FilterZalozil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtr Objednávka.
        /// </summary>
        public static string FiltrObj {
            get {
                return ResourceManager.GetString("FiltrObj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtr Stav.
        /// </summary>
        public static string FiltrStav {
            get {
                return ResourceManager.GetString("FiltrStav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hlavní řada.
        /// </summary>
        public static string HlavniRada {
            get {
                return ResourceManager.GetString("HlavniRada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KST.
        /// </summary>
        public static string KST {
            get {
                return ResourceManager.GetString("KST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Měna.
        /// </summary>
        public static string Mena {
            get {
                return ResourceManager.GetString("Mena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nastavit.
        /// </summary>
        public static string Nastavit {
            get {
                return ResourceManager.GetString("Nastavit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Číslo objednávky.
        /// </summary>
        public static string ObjCislo {
            get {
                return ResourceManager.GetString("ObjCislo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Počet položek.
        /// </summary>
        public static string PocetPolozek {
            get {
                return ResourceManager.GetString("PocetPolozek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obsah položky:.
        /// </summary>
        public static string PolozkaObsah {
            get {
                return ResourceManager.GetString("PolozkaObsah", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popis požadavku.
        /// </summary>
        public static string Popis {
            get {
                return ResourceManager.GetString("Popis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Číslo požadavku.
        /// </summary>
        public static string PozCislo {
            get {
                return ResourceManager.GetString("PozCislo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stav.
        /// </summary>
        public static string Stav {
            get {
                return ResourceManager.GetString("Stav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vlastní SQL podmínka (WHERE), např: Zalozil LIKE &apos;%ma%&apos; nebo i.InterniPoznamka like &apos;%pod%&apos;.
        /// </summary>
        public static string VlastniSQL {
            get {
                return ResourceManager.GetString("VlastniSQL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sloupec v podmínce (položka).
        /// </summary>
        public static string VlastniSQLSloupecPolozka {
            get {
                return ResourceManager.GetString("VlastniSQLSloupecPolozka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sloupec v podmínce (požadavek).
        /// </summary>
        public static string VlastniSQLSloupecPozadavek {
            get {
                return ResourceManager.GetString("VlastniSQLSloupecPozadavek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vymazat.
        /// </summary>
        public static string Vymazat {
            get {
                return ResourceManager.GetString("Vymazat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Založil.
        /// </summary>
        public static string Zalozil {
            get {
                return ResourceManager.GetString("Zalozil", resourceCulture);
            }
        }
    }
}
