//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JULI_IS.Resources.Pozadavky {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Grid {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Grid() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JULI_IS.Resources.Pozadavky.Grid", typeof(Grid).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresa.
        /// </summary>
        public static string Adresa {
            get {
                return ResourceManager.GetString("Adresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automaticky odeslat.
        /// </summary>
        public static string AutomatSend {
            get {
                return ResourceManager.GetString("AutomatSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avízo o dodávce.
        /// </summary>
        public static string Avizo {
            get {
                return ResourceManager.GetString("Avizo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odeslat zakladateli požadavku avízo o dodávce?.
        /// </summary>
        public static string AvizoConfirm {
            get {
                return ResourceManager.GetString("AvizoConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Celková cena.
        /// </summary>
        public static string CelkovaCena {
            get {
                return ResourceManager.GetString("CelkovaCena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Číslo.
        /// </summary>
        public static string Cislo {
            get {
                return ResourceManager.GetString("Cislo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum dodání.
        /// </summary>
        public static string DateDelivery {
            get {
                return ResourceManager.GetString("DateDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum.
        /// </summary>
        public static string Datum {
            get {
                return ResourceManager.GetString("Datum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum vytvoření.
        /// </summary>
        public static string DatumVytv {
            get {
                return ResourceManager.GetString("DatumVytv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodavatel.
        /// </summary>
        public static string Dodavatel {
            get {
                return ResourceManager.GetString("Dodavatel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interní poznámka.
        /// </summary>
        public static string InterniPozn {
            get {
                return ResourceManager.GetString("InterniPozn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jednotková cena.
        /// </summary>
        public static string JednCena {
            get {
                return ResourceManager.GetString("JednCena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jednotka.
        /// </summary>
        public static string Jednotka {
            get {
                return ResourceManager.GetString("Jednotka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jméno souboru.
        /// </summary>
        public static string JmenoSouboru {
            get {
                return ResourceManager.GetString("JmenoSouboru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kopie.
        /// </summary>
        public static string Kopie {
            get {
                return ResourceManager.GetString("Kopie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KST.
        /// </summary>
        public static string KST {
            get {
                return ResourceManager.GetString("KST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KST / Konto.
        /// </summary>
        public static string KSTKonto {
            get {
                return ResourceManager.GetString("KSTKonto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Měna.
        /// </summary>
        public static string Mena {
            get {
                return ResourceManager.GetString("Mena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Množství.
        /// </summary>
        public static string Mnozstvi {
            get {
                return ResourceManager.GetString("Mnozstvi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Číslo nabídky.
        /// </summary>
        public static string NabCislo {
            get {
                return ResourceManager.GetString("NabCislo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Název.
        /// </summary>
        public static string Nazev {
            get {
                return ResourceManager.GetString("Nazev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neodesílat.
        /// </summary>
        public static string Neodesilat {
            get {
                return ResourceManager.GetString("Neodesilat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Číslo objednávky.
        /// </summary>
        public static string ObjCislo {
            get {
                return ResourceManager.GetString("ObjCislo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objednávka.
        /// </summary>
        public static string Objednavka {
            get {
                return ResourceManager.GetString("Objednavka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Počet položek.
        /// </summary>
        public static string PocetPolozek {
            get {
                return ResourceManager.GetString("PocetPolozek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opravdu změnit stav položky?.
        /// </summary>
        public static string PolozkaZmenitConfirm {
            get {
                return ResourceManager.GetString("PolozkaZmenitConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popis požadavku.
        /// </summary>
        public static string Popis {
            get {
                return ResourceManager.GetString("Popis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popis objednávky.
        /// </summary>
        public static string PopisObj {
            get {
                return ResourceManager.GetString("PopisObj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popis položky.
        /// </summary>
        public static string PopisPolozka {
            get {
                return ResourceManager.GetString("PopisPolozka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popis.
        /// </summary>
        public static string PopisSouboru {
            get {
                return ResourceManager.GetString("PopisSouboru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uložit popis.
        /// </summary>
        public static string PopisUlozit {
            get {
                return ResourceManager.GetString("PopisUlozit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Požadavek.
        /// </summary>
        public static string Pozadavek {
            get {
                return ResourceManager.GetString("Pozadavek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Číslo požadavku.
        /// </summary>
        public static string PozCislo {
            get {
                return ResourceManager.GetString("PozCislo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schválit.
        /// </summary>
        public static string Schvalit {
            get {
                return ResourceManager.GetString("Schvalit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opravdu schválit požadavek?.
        /// </summary>
        public static string SchvalitPotvrzeni {
            get {
                return ResourceManager.GetString("SchvalitPotvrzeni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stav.
        /// </summary>
        public static string Stav {
            get {
                return ResourceManager.GetString("Stav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stav objednávky.
        /// </summary>
        public static string StavObj {
            get {
                return ResourceManager.GetString("StavObj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Termín dodání.
        /// </summary>
        public static string TerminDodani {
            get {
                return ResourceManager.GetString("TerminDodani", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Před odesláním upravit.
        /// </summary>
        public static string Upravit {
            get {
                return ResourceManager.GetString("Upravit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vymazat.
        /// </summary>
        public static string Vymazat {
            get {
                return ResourceManager.GetString("Vymazat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vymazat soubor.
        /// </summary>
        public static string VymazatSoubor {
            get {
                return ResourceManager.GetString("VymazatSoubor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Založil.
        /// </summary>
        public static string Zalozil {
            get {
                return ResourceManager.GetString("Zalozil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zamítnout.
        /// </summary>
        public static string Zamitnout {
            get {
                return ResourceManager.GetString("Zamitnout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opravdu požadavek zamítnout?.
        /// </summary>
        public static string ZamitnoutPotvrzeni {
            get {
                return ResourceManager.GetString("ZamitnoutPotvrzeni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zboží dodáno.
        /// </summary>
        public static string ZboziDodano {
            get {
                return ResourceManager.GetString("ZboziDodano", resourceCulture);
            }
        }
    }
}
