//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JULI_IS.Resources.Pozadavky {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ModalDodavatel {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ModalDodavatel() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JULI_IS.Resources.Pozadavky.ModalDodavatel", typeof(ModalDodavatel).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Číslo dodavatele.
        /// </summary>
        public static string Cislo {
            get {
                return ResourceManager.GetString("Cislo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email dodavatele.
        /// </summary>
        public static string EmailDodavatele {
            get {
                return ResourceManager.GetString("EmailDodavatele", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax.
        /// </summary>
        public static string Fax {
            get {
                return ResourceManager.GetString("Fax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontaktní osoba.
        /// </summary>
        public static string KontaktOs {
            get {
                return ResourceManager.GetString("KontaktOs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email kontaktní osoby.
        /// </summary>
        public static string KontaktOsEmail {
            get {
                return ResourceManager.GetString("KontaktOsEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Měna.
        /// </summary>
        public static string Mena {
            get {
                return ResourceManager.GetString("Mena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Město.
        /// </summary>
        public static string Mesto {
            get {
                return ResourceManager.GetString("Mesto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Načíst dodavatele z S21.
        /// </summary>
        public static string NacistS21 {
            get {
                return ResourceManager.GetString("NacistS21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail dodavatele.
        /// </summary>
        public static string Nadpis {
            get {
                return ResourceManager.GetString("Nadpis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Název dodavatele.
        /// </summary>
        public static string Nazev {
            get {
                return ResourceManager.GetString("Nazev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nový dodavatel.
        /// </summary>
        public static string Novy {
            get {
                return ResourceManager.GetString("Novy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PSČ.
        /// </summary>
        public static string PSC {
            get {
                return ResourceManager.GetString("PSC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Společnost.
        /// </summary>
        public static string Spolecnost {
            get {
                return ResourceManager.GetString("Spolecnost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon.
        /// </summary>
        public static string Telefon {
            get {
                return ResourceManager.GetString("Telefon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ulice.
        /// </summary>
        public static string Ulice {
            get {
                return ResourceManager.GetString("Ulice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ulice / Město.
        /// </summary>
        public static string UliceMesto {
            get {
                return ResourceManager.GetString("UliceMesto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uložit.
        /// </summary>
        public static string Ulozit {
            get {
                return ResourceManager.GetString("Ulozit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kód země.
        /// </summary>
        public static string Zeme {
            get {
                return ResourceManager.GetString("Zeme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zrušit.
        /// </summary>
        public static string Zrusit {
            get {
                return ResourceManager.GetString("Zrusit", resourceCulture);
            }
        }
    }
}
