//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JULI_IS.Resources.Pozadavky {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PagePolozky {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PagePolozky() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JULI_IS.Resources.Pozadavky.PagePolozky", typeof(PagePolozky).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aktuálního uživatele.
        /// </summary>
        public static string AktUziv {
            get {
                return ResourceManager.GetString("AktUziv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nenalezeny žádné požadavky!.
        /// </summary>
        public static string NoPolozky {
            get {
                return ResourceManager.GetString("NoPolozky", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nový požadavek.
        /// </summary>
        public static string NovyPoz {
            get {
                return ResourceManager.GetString("NovyPoz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Celkový počet položek:.
        /// </summary>
        public static string PocetPolozek {
            get {
                return ResourceManager.GetString("PocetPolozek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opravdu zkopírovat požadavek? Vytvoří se kopie i připojených souborů.
        /// </summary>
        public static string PozadavekCopy {
            get {
                return ResourceManager.GetString("PozadavekCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prehled požadavků po položkách.
        /// </summary>
        public static string PrehledPolozek {
            get {
                return ResourceManager.GetString("PrehledPolozek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inteligentní hledaní dodavatelů.
        /// </summary>
        public static string SmartDodavatele {
            get {
                return ResourceManager.GetString("SmartDodavatele", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to všechny.
        /// </summary>
        public static string Vsechny {
            get {
                return ResourceManager.GetString("Vsechny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vypsat požadavky pouze pro.
        /// </summary>
        public static string VypsatPouze {
            get {
                return ResourceManager.GetString("VypsatPouze", resourceCulture);
            }
        }
    }
}
