//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JULI_IS.Resources.Pozadavky {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PageObjednavkySign {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PageObjednavkySign() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JULI_IS.Resources.Pozadavky.PageObjednavkySign", typeof(PageObjednavkySign).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prosím vyberte důvod zamítnutí objednávky nebo zadejte vlastní:.
        /// </summary>
        public static string DuvodZamitnuti {
            get {
                return ResourceManager.GetString("DuvodZamitnuti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prosím popište důvod:.
        /// </summary>
        public static string DuvodZamitnutiPopis {
            get {
                return ResourceManager.GetString("DuvodZamitnutiPopis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podpis objednávek.
        /// </summary>
        public static string Nadpis {
            get {
                return ResourceManager.GetString("Nadpis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nenalezeny žádné objednávky!.
        /// </summary>
        public static string NoPolozky {
            get {
                return ResourceManager.GetString("NoPolozky", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Počet objednávek:.
        /// </summary>
        public static string PocetObj {
            get {
                return ResourceManager.GetString("PocetObj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opravdu objednávku schválit?.
        /// </summary>
        public static string SchvalitConfirm {
            get {
                return ResourceManager.GetString("SchvalitConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opravdu objednávku ODESLAT dodavateli?.
        /// </summary>
        public static string SendConfirm {
            get {
                return ResourceManager.GetString("SendConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vrátit do tvorby objednávek.
        /// </summary>
        public static string Vratit {
            get {
                return ResourceManager.GetString("Vratit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opravdu objednávku zamítnout?.
        /// </summary>
        public static string ZamitnoutConfirm {
            get {
                return ResourceManager.GetString("ZamitnoutConfirm", resourceCulture);
            }
        }
    }
}
