//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JULI_IS.Resources.Pozadavky {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PagePozadavkySign {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PagePozadavkySign() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JULI_IS.Resources.Pozadavky.PagePozadavkySign", typeof(PagePozadavkySign).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aktuálního uživatele.
        /// </summary>
        public static string AktUziv {
            get {
                return ResourceManager.GetString("AktUziv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prosím vyberte důvod zamítnutí požadavku nebo zadejte vlastní.
        /// </summary>
        public static string DuvodZamitnuti {
            get {
                return ResourceManager.GetString("DuvodZamitnuti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prosím popište důvod.
        /// </summary>
        public static string DuvodZamitnutiPopis {
            get {
                return ResourceManager.GetString("DuvodZamitnutiPopis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podpis požadavků.
        /// </summary>
        public static string Nadpis {
            get {
                return ResourceManager.GetString("Nadpis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nenalezeny žádné požadavky!.
        /// </summary>
        public static string NoPozadavky {
            get {
                return ResourceManager.GetString("NoPozadavky", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nový požadavek.
        /// </summary>
        public static string NovyPoz {
            get {
                return ResourceManager.GetString("NovyPoz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Počet požadavků.
        /// </summary>
        public static string Pocet {
            get {
                return ResourceManager.GetString("Pocet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Celkový přehled požadavků.
        /// </summary>
        public static string PrehledPozadavku {
            get {
                return ResourceManager.GetString("PrehledPozadavku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to všechny.
        /// </summary>
        public static string Vsechny {
            get {
                return ResourceManager.GetString("Vsechny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vypsat požadavky pouze pro.
        /// </summary>
        public static string VypsatPouze {
            get {
                return ResourceManager.GetString("VypsatPouze", resourceCulture);
            }
        }
    }
}
