//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JULI_IS.Resources.Pozadavky {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PageObjednavkyTvorba {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PageObjednavkyTvorba() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JULI_IS.Resources.Pozadavky.PageObjednavkyTvorba", typeof(PageObjednavkyTvorba).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opravdu vymazat položku z tvorby objednavek? Položka se vrátí zpět do požadavků!.
        /// </summary>
        public static string DeleteConfirm {
            get {
                return ResourceManager.GetString("DeleteConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tvorba objednávky.
        /// </summary>
        public static string Nadpis {
            get {
                return ResourceManager.GetString("Nadpis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nenalezeny žádné požadavky!.
        /// </summary>
        public static string NoPolozky {
            get {
                return ResourceManager.GetString("NoPolozky", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to přidat do obj..
        /// </summary>
        public static string ObjAdd {
            get {
                return ResourceManager.GetString("ObjAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Počet položek:.
        /// </summary>
        public static string PocetPolozek {
            get {
                return ResourceManager.GetString("PocetPolozek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přidat.
        /// </summary>
        public static string Pridat {
            get {
                return ResourceManager.GetString("Pridat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tvorba.
        /// </summary>
        public static string Tvorba {
            get {
                return ResourceManager.GetString("Tvorba", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vyberte č. objednávky.
        /// </summary>
        public static string VybratCislo {
            get {
                return ResourceManager.GetString("VybratCislo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vytvořit.
        /// </summary>
        public static string Vytvorit {
            get {
                return ResourceManager.GetString("Vytvorit", resourceCulture);
            }
        }
    }
}
