//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JULI_IS.Resources.Pozadavky {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PageObjednavkaDetail {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PageObjednavkaDetail() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JULI_IS.Resources.Pozadavky.PageObjednavkaDetail", typeof(PageObjednavkaDetail).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přidat položku.
        /// </summary>
        public static string AddItem {
            get {
                return ResourceManager.GetString("AddItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ANO.
        /// </summary>
        public static string Ano {
            get {
                return ResourceManager.GetString("Ano", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Požadavek vytisknut.
        /// </summary>
        public static string BtnTisk {
            get {
                return ResourceManager.GetString("BtnTisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vrátit objednávku (vyřadit z podpisů).
        /// </summary>
        public static string CancelObj {
            get {
                return ResourceManager.GetString("CancelObj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Celková cena.
        /// </summary>
        public static string CelkovaCena {
            get {
                return ResourceManager.GetString("CelkovaCena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum.
        /// </summary>
        public static string Datum {
            get {
                return ResourceManager.GetString("Datum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objednávka schválena dne:.
        /// </summary>
        public static string DatumObjSchvalena {
            get {
                return ResourceManager.GetString("DatumObjSchvalena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum odeslání:.
        /// </summary>
        public static string DatumOdeslani {
            get {
                return ResourceManager.GetString("DatumOdeslani", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opravdu odstranit položku z objednávky?.
        /// </summary>
        public static string DeleteItemConfirm {
            get {
                return ResourceManager.GetString("DeleteItemConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dne:.
        /// </summary>
        public static string Dne {
            get {
                return ResourceManager.GetString("Dne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodací podmínky.
        /// </summary>
        public static string DodaciPodm {
            get {
                return ResourceManager.GetString("DodaciPodm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vyberte dodací podmínku....
        /// </summary>
        public static string DodPodmVyber {
            get {
                return ResourceManager.GetString("DodPodmVyber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dokončena.
        /// </summary>
        public static string dokoncena {
            get {
                return ResourceManager.GetString("dokoncena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Druh ceny.
        /// </summary>
        public static string DruhCeny {
            get {
                return ResourceManager.GetString("DruhCeny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vyberte druh ceny....
        /// </summary>
        public static string DruhCenyVyber {
            get {
                return ResourceManager.GetString("DruhCenyVyber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Důvod:.
        /// </summary>
        public static string Duvod {
            get {
                return ResourceManager.GetString("Duvod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nový / Edit dodavatele.
        /// </summary>
        public static string EditDodavatele {
            get {
                return ResourceManager.GetString("EditDodavatele", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to po výběru dodavatele klikněte na tlačítko pro přiřazení dodavatele k požadavku.
        /// </summary>
        public static string EditDodavatelePopis {
            get {
                return ResourceManager.GetString("EditDodavatelePopis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opravdu soubor vymazat?.
        /// </summary>
        public static string fileDeleteConfirm {
            get {
                return ResourceManager.GetString("fileDeleteConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soubory byly v pořádku nahrány..
        /// </summary>
        public static string fileSuccessMessageText {
            get {
                return ResourceManager.GetString("fileSuccessMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nahrát soubory (pro výběr více souborů podržte klávesu CTRL).
        /// </summary>
        public static string fileUploadButtonText {
            get {
                return ResourceManager.GetString("fileUploadButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chyba během nahrávání souborů!.
        /// </summary>
        public static string fileUploadErrorMessageText {
            get {
                return ResourceManager.GetString("fileUploadErrorMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hlavní řada.
        /// </summary>
        public static string HlRada {
            get {
                return ResourceManager.GetString("HlRada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interní číslo.
        /// </summary>
        public static string IntCislo {
            get {
                return ResourceManager.GetString("IntCislo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interní poznámka.
        /// </summary>
        public static string IntPoznamka {
            get {
                return ResourceManager.GetString("IntPoznamka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plánovaná investice.
        /// </summary>
        public static string InvesticePlan {
            get {
                return ResourceManager.GetString("InvesticePlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jiný materiál nebo systém jiného Dodavatel by byly pro JULI Motorenwerk zcela nevyhovující a nekompatibilní z pohledu již zavedené současné i budoucí výroby nebo provozu JULI Motorenwerk.
        /// </summary>
        public static string JinyNevyhovuje {
            get {
                return ResourceManager.GetString("JinyNevyhovuje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jméno.
        /// </summary>
        public static string Jmeno {
            get {
                return ResourceManager.GetString("Jmeno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KST.
        /// </summary>
        public static string kst {
            get {
                return ResourceManager.GetString("kst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vyberte KST.
        /// </summary>
        public static string kstVyber {
            get {
                return ResourceManager.GetString("kstVyber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Měna.
        /// </summary>
        public static string mena {
            get {
                return ResourceManager.GetString("mena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OBJEDNÁVKA JE UŽ ODESLÁNA NA SCHVÁLENÍ!!.
        /// </summary>
        public static string ModalConfirm1 {
            get {
                return ResourceManager.GetString("ModalConfirm1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uložením objednávky přestane platit odeslání a bude nutné ji odeslat znovu na podpis!.
        /// </summary>
        public static string ModalConfirm2 {
            get {
                return ResourceManager.GetString("ModalConfirm2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opravdu objednávku uložit?.
        /// </summary>
        public static string ModalConfirm3 {
            get {
                return ResourceManager.GetString("ModalConfirm3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potvrzení.
        /// </summary>
        public static string ModalConfirmNadpis {
            get {
                return ResourceManager.GetString("ModalConfirmNadpis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modelové zařízení.
        /// </summary>
        public static string ModelZar {
            get {
                return ResourceManager.GetString("ModelZar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Číslo nabídky.
        /// </summary>
        public static string NabidkaCislo {
            get {
                return ResourceManager.GetString("NabidkaCislo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail objednávky.
        /// </summary>
        public static string nadpis {
            get {
                return ResourceManager.GetString("nadpis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Náhled objednávky.
        /// </summary>
        public static string NahledObj {
            get {
                return ResourceManager.GetString("NahledObj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Náhled potvrzení.
        /// </summary>
        public static string NahledPotvrzeni {
            get {
                return ResourceManager.GetString("NahledPotvrzeni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ostatní nákupy.
        /// </summary>
        public static string NakupyOst {
            get {
                return ResourceManager.GetString("NakupyOst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Název dodavatele.
        /// </summary>
        public static string NazevDodavatele {
            get {
                return ResourceManager.GetString("NazevDodavatele", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objednávka se NEBUDE odesílat..
        /// </summary>
        public static string NebudeOdeslana {
            get {
                return ResourceManager.GetString("NebudeOdeslana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEODESÍLAT.
        /// </summary>
        public static string Neodesilat {
            get {
                return ResourceManager.GetString("Neodesilat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neodesláno.
        /// </summary>
        public static string Neodeslano {
            get {
                return ResourceManager.GetString("Neodeslano", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nepodepsáno.
        /// </summary>
        public static string Nepodepsano {
            get {
                return ResourceManager.GetString("Nepodepsano", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neuvedeno.
        /// </summary>
        public static string neuvedeno {
            get {
                return ResourceManager.GetString("neuvedeno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neveřejný požadavek.
        /// </summary>
        public static string neverejny {
            get {
                return ResourceManager.GetString("neverejny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objednávka číslo.
        /// </summary>
        public static string ObjCislo {
            get {
                return ResourceManager.GetString("ObjCislo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objednávka.
        /// </summary>
        public static string Objednavka {
            get {
                return ResourceManager.GetString("Objednavka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objednávka byla.
        /// </summary>
        public static string ObjednavkaByla {
            get {
                return ResourceManager.GetString("ObjednavkaByla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objednávku je možné odeslat.
        /// </summary>
        public static string ObjednavkaNaOdesl {
            get {
                return ResourceManager.GetString("ObjednavkaNaOdesl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objednávku neodesílat.
        /// </summary>
        public static string ObjNeodesilat {
            get {
                return ResourceManager.GetString("ObjNeodesilat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objednávka vytvořena a odeslána na schválení!.
        /// </summary>
        public static string ObjVytvorena {
            get {
                return ResourceManager.GetString("ObjVytvorena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odesláno.
        /// </summary>
        public static string Odeslano {
            get {
                return ResourceManager.GetString("Odeslano", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odesláno ke schválení.
        /// </summary>
        public static string OdeslanoVedouci {
            get {
                return ResourceManager.GetString("OdeslanoVedouci", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vygeneruje se PDF soubor, který se zároveň uloží mezi přiložené soubory..
        /// </summary>
        public static string PDFgen {
            get {
                return ResourceManager.GetString("PDFgen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vlastní text platby.
        /// </summary>
        public static string PlatbaVlastniText {
            get {
                return ResourceManager.GetString("PlatbaVlastniText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Platební podmínky.
        /// </summary>
        public static string PlatPodm {
            get {
                return ResourceManager.GetString("PlatPodm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vyberte platební podmínku....
        /// </summary>
        public static string PlatPodmVyber {
            get {
                return ResourceManager.GetString("PlatPodmVyber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Počet položek:.
        /// </summary>
        public static string PocetPol {
            get {
                return ResourceManager.GetString("PocetPol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podepsáno.
        /// </summary>
        public static string Podepsano {
            get {
                return ResourceManager.GetString("Podepsano", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podepsáno ředitel nebo controling a odesláno na objednání:.
        /// </summary>
        public static string PodepsanoReditel {
            get {
                return ResourceManager.GetString("PodepsanoReditel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podepsáno vedoucím.
        /// </summary>
        public static string PodepsanoVedouci {
            get {
                return ResourceManager.GetString("PodepsanoVedouci", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Položky v objednávce.
        /// </summary>
        public static string PolObj {
            get {
                return ResourceManager.GetString("PolObj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Celkový popis (nadpis) požadavku.
        /// </summary>
        public static string popis {
            get {
                return ResourceManager.GetString("popis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prosím popište důvod:.
        /// </summary>
        public static string PopisteDuvody {
            get {
                return ResourceManager.GetString("PopisteDuvody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poptány nejméně tři společnosti?.
        /// </summary>
        public static string Poptany3 {
            get {
                return ResourceManager.GetString("Poptany3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Požadavek můžete poslat znovu na schválení!.
        /// </summary>
        public static string PozadavekPozn1 {
            get {
                return ResourceManager.GetString("PozadavekPozn1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Požadavek založen dne.
        /// </summary>
        public static string PozadavekZalozen {
            get {
                return ResourceManager.GetString("PozadavekZalozen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Požadavek byl ZAMÍTNUT!.
        /// </summary>
        public static string PozadavekZamitnut {
            get {
                return ResourceManager.GetString("PozadavekZamitnut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poznámka.
        /// </summary>
        public static string Poznamka {
            get {
                return ResourceManager.GetString("Poznamka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poznámky z požadavků.
        /// </summary>
        public static string PoznPoz {
            get {
                return ResourceManager.GetString("PoznPoz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přiložené soubory.
        /// </summary>
        public static string PrilozeneSoubory {
            get {
                return ResourceManager.GetString("PrilozeneSoubory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přiřadit dodavatele k požadavku.
        /// </summary>
        public static string PriraditDodavatele {
            get {
                return ResourceManager.GetString("PriraditDodavatele", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rozúčtovat.
        /// </summary>
        public static string Rozuctovat {
            get {
                return ResourceManager.GetString("Rozuctovat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zadejte množství, které patří k této položce, ze zbylého množství bude vytvořena nová položka.
        /// </summary>
        public static string RozuctovatPopis {
            get {
                return ResourceManager.GetString("RozuctovatPopis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schvalovatel.
        /// </summary>
        public static string Schalovatel {
            get {
                return ResourceManager.GetString("Schalovatel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STORNOVÁNA!.
        /// </summary>
        public static string storno {
            get {
                return ResourceManager.GetString("storno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STORNO objednávky.
        /// </summary>
        public static string StornoObj {
            get {
                return ResourceManager.GetString("StornoObj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opravdu objednávku STORNOVAT?!?.
        /// </summary>
        public static string StornoPotvrzeni {
            get {
                return ResourceManager.GetString("StornoPotvrzeni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TISK.
        /// </summary>
        public static string Tisk {
            get {
                return ResourceManager.GetString("Tisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typ investice.
        /// </summary>
        public static string TypInvestice {
            get {
                return ResourceManager.GetString("TypInvestice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ukončit.
        /// </summary>
        public static string Ukoncit {
            get {
                return ResourceManager.GetString("Ukoncit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uložit koncept objednávky.
        /// </summary>
        public static string UlozitKoncept {
            get {
                return ResourceManager.GetString("UlozitKoncept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to uživatelem.
        /// </summary>
        public static string Uzivatelem {
            get {
                return ResourceManager.GetString("Uzivatelem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prosím zadejte vlastní text.
        /// </summary>
        public static string VlText {
            get {
                return ResourceManager.GetString("VlText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vybraný dodavatel.
        /// </summary>
        public static string VybrDodavatel {
            get {
                return ResourceManager.GetString("VybrDodavatel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vyřadit položku z objednávky.
        /// </summary>
        public static string VyraditPolozku {
            get {
                return ResourceManager.GetString("VyraditPolozku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objednávka &lt;b&gt;vytisknutá&lt;/b&gt; dne.
        /// </summary>
        public static string VytisknutoDne {
            get {
                return ResourceManager.GetString("VytisknutoDne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objednávka vytisknuta dne.
        /// </summary>
        public static string Vytisteno {
            get {
                return ResourceManager.GetString("Vytisteno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Založil.
        /// </summary>
        public static string zalozil {
            get {
                return ResourceManager.GetString("zalozil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZAMÍTNUTA!.
        /// </summary>
        public static string zamitnuta {
            get {
                return ResourceManager.GetString("zamitnuta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zařadit objednávku.
        /// </summary>
        public static string ZaraditObjednavku {
            get {
                return ResourceManager.GetString("ZaraditObjednavku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opravdu objednávku zařadit a odeslat na schválení?.
        /// </summary>
        public static string ZaraditObjednavkuPotvrzeni {
            get {
                return ResourceManager.GetString("ZaraditObjednavkuPotvrzeni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V zastoupení (jméno.příjmení).
        /// </summary>
        public static string zastoupeni {
            get {
                return ResourceManager.GetString("zastoupeni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zdůvodnění.
        /// </summary>
        public static string Zduvodneni {
            get {
                return ResourceManager.GetString("Zduvodneni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Způsob platby.
        /// </summary>
        public static string ZpusobPlatby {
            get {
                return ResourceManager.GetString("ZpusobPlatby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zvolte číslo investice ....
        /// </summary>
        public static string ZvolteCisloInvestice {
            get {
                return ResourceManager.GetString("ZvolteCisloInvestice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zvolte dodavatele ....
        /// </summary>
        public static string ZvolteDodavatele {
            get {
                return ResourceManager.GetString("ZvolteDodavatele", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zvolte číslo konta ....
        /// </summary>
        public static string ZvolteKonto {
            get {
                return ResourceManager.GetString("ZvolteKonto", resourceCulture);
            }
        }
    }
}
