//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JULI_IS.Resources.Pozadavky {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PagePozadavkyDetail {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PagePozadavkyDetail() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JULI_IS.Resources.Pozadavky.PagePozadavkyDetail", typeof(PagePozadavkyDetail).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přidat položku.
        /// </summary>
        public static string AddItem {
            get {
                return ResourceManager.GetString("AddItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ANO.
        /// </summary>
        public static string Ano {
            get {
                return ResourceManager.GetString("Ano", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Požadavek vytisknut.
        /// </summary>
        public static string BtnTisk {
            get {
                return ResourceManager.GetString("BtnTisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Celková cena.
        /// </summary>
        public static string CelkovaCena {
            get {
                return ResourceManager.GetString("CelkovaCena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum.
        /// </summary>
        public static string Datum {
            get {
                return ResourceManager.GetString("Datum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opravdu vymazat položku z požadavku?.
        /// </summary>
        public static string DeleteItemConfirm {
            get {
                return ResourceManager.GetString("DeleteItemConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dne.
        /// </summary>
        public static string Dne {
            get {
                return ResourceManager.GetString("Dne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Důvod.
        /// </summary>
        public static string Duvod {
            get {
                return ResourceManager.GetString("Duvod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nový / Edit dodavatele.
        /// </summary>
        public static string EditDodavatele {
            get {
                return ResourceManager.GetString("EditDodavatele", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to po výběru dodavatele klikněte na tlačítko pro přiřazení dodavatele k požadavku.
        /// </summary>
        public static string EditDodavatelePopis {
            get {
                return ResourceManager.GetString("EditDodavatelePopis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opravdu soubor vymazat?.
        /// </summary>
        public static string fileDeleteConfirm {
            get {
                return ResourceManager.GetString("fileDeleteConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soubory byly v pořádku nahrány..
        /// </summary>
        public static string fileSuccessMessageText {
            get {
                return ResourceManager.GetString("fileSuccessMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nahrát soubory (pro výběr více souborů podržte klávesu CTRL).
        /// </summary>
        public static string fileUploadButtonText {
            get {
                return ResourceManager.GetString("fileUploadButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chyba během nahrávání souborů!.
        /// </summary>
        public static string fileUploadErrorMessageText {
            get {
                return ResourceManager.GetString("fileUploadErrorMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interní poznámka.
        /// </summary>
        public static string IntPoznamka {
            get {
                return ResourceManager.GetString("IntPoznamka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plánovaná investice.
        /// </summary>
        public static string InvesticePlan {
            get {
                return ResourceManager.GetString("InvesticePlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jiný materiál nebo systém jiného Dodavatel by byly pro JULI Motorenwerk zcela nevyhovující a nekompatibilní z pohledu již zavedené současné i budoucí výroby nebo provozu JULI Motorenwerk.
        /// </summary>
        public static string JinyNevyhovuje {
            get {
                return ResourceManager.GetString("JinyNevyhovuje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jméno.
        /// </summary>
        public static string Jmeno {
            get {
                return ResourceManager.GetString("Jmeno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KST (pokud je jednotné pro celý požadavek).
        /// </summary>
        public static string kst {
            get {
                return ResourceManager.GetString("kst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vyberte KST.
        /// </summary>
        public static string kstVyber {
            get {
                return ResourceManager.GetString("kstVyber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Měna.
        /// </summary>
        public static string mena {
            get {
                return ResourceManager.GetString("mena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POŽADAVEK JE UŽ ODESLÁN NEBO TAKÉ PODEPSÁN!!.
        /// </summary>
        public static string ModalConfirm1 {
            get {
                return ResourceManager.GetString("ModalConfirm1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uložením požadavku přestane platit jeho schválení a bude nutné ho odeslat znovu na podpis!.
        /// </summary>
        public static string ModalConfirm2 {
            get {
                return ResourceManager.GetString("ModalConfirm2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opravdu požadavek uložit?.
        /// </summary>
        public static string ModalConfirm3 {
            get {
                return ResourceManager.GetString("ModalConfirm3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potvrzení.
        /// </summary>
        public static string ModalConfirmNadpis {
            get {
                return ResourceManager.GetString("ModalConfirmNadpis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modelové zařízení.
        /// </summary>
        public static string ModelZar {
            get {
                return ResourceManager.GetString("ModelZar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Číslo nabídky.
        /// </summary>
        public static string NabidkaCislo {
            get {
                return ResourceManager.GetString("NabidkaCislo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail požadavku.
        /// </summary>
        public static string nadpis {
            get {
                return ResourceManager.GetString("nadpis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ostatní nákupy.
        /// </summary>
        public static string NakupyOst {
            get {
                return ResourceManager.GetString("NakupyOst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Název dodavatele.
        /// </summary>
        public static string NazevDodavatele {
            get {
                return ResourceManager.GetString("NazevDodavatele", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neodesláno.
        /// </summary>
        public static string Neodeslano {
            get {
                return ResourceManager.GetString("Neodeslano", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nepodepsáno.
        /// </summary>
        public static string Nepodepsano {
            get {
                return ResourceManager.GetString("Nepodepsano", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neuvedeno.
        /// </summary>
        public static string neuvedeno {
            get {
                return ResourceManager.GetString("neuvedeno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neveřejný požadavek.
        /// </summary>
        public static string neverejny {
            get {
                return ResourceManager.GetString("neverejny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objednávku neodesílat.
        /// </summary>
        public static string ObjNeodesilat {
            get {
                return ResourceManager.GetString("ObjNeodesilat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odesláno.
        /// </summary>
        public static string Odeslano {
            get {
                return ResourceManager.GetString("Odeslano", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odesláno ke schválení.
        /// </summary>
        public static string OdeslanoVedouci {
            get {
                return ResourceManager.GetString("OdeslanoVedouci", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vygeneruje se PDF soubor, který se zároveň uloží mezi přiložené soubory..
        /// </summary>
        public static string PDFgen {
            get {
                return ResourceManager.GetString("PDFgen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vlastní text platby.
        /// </summary>
        public static string PlatbaVlastniText {
            get {
                return ResourceManager.GetString("PlatbaVlastniText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Počet položek:.
        /// </summary>
        public static string PocetPol {
            get {
                return ResourceManager.GetString("PocetPol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podepsáno.
        /// </summary>
        public static string Podepsano {
            get {
                return ResourceManager.GetString("Podepsano", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podepsáno ředitel nebo controling a odesláno na objednání:.
        /// </summary>
        public static string PodepsanoReditel {
            get {
                return ResourceManager.GetString("PodepsanoReditel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podepsáno vedoucím.
        /// </summary>
        public static string PodepsanoVedouci {
            get {
                return ResourceManager.GetString("PodepsanoVedouci", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Celkový popis (nadpis) požadavku.
        /// </summary>
        public static string popis {
            get {
                return ResourceManager.GetString("popis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prosím popište důvod:.
        /// </summary>
        public static string PopisteDuvody {
            get {
                return ResourceManager.GetString("PopisteDuvody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poptány nejméně tři společnosti?.
        /// </summary>
        public static string Poptany3 {
            get {
                return ResourceManager.GetString("Poptany3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Požadavek číslo.
        /// </summary>
        public static string PozadavekCislo {
            get {
                return ResourceManager.GetString("PozadavekCislo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Požadavek můžete poslat znovu na schválení!.
        /// </summary>
        public static string PozadavekPozn1 {
            get {
                return ResourceManager.GetString("PozadavekPozn1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Požadavek založen dne.
        /// </summary>
        public static string PozadavekZalozen {
            get {
                return ResourceManager.GetString("PozadavekZalozen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Požadavek byl ZAMÍTNUT!.
        /// </summary>
        public static string PozadavekZamitnut {
            get {
                return ResourceManager.GetString("PozadavekZamitnut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poznámka.
        /// </summary>
        public static string Poznamka {
            get {
                return ResourceManager.GetString("Poznamka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přiložené soubory.
        /// </summary>
        public static string PrilozeneSoubory {
            get {
                return ResourceManager.GetString("PrilozeneSoubory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přiřadit dodavatele k požadavku.
        /// </summary>
        public static string PriraditDodavatele {
            get {
                return ResourceManager.GetString("PriraditDodavatele", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rozúčtovat.
        /// </summary>
        public static string Rozuctovat {
            get {
                return ResourceManager.GetString("Rozuctovat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zadejte množství, které patří k této položce, ze zbylého množství bude vytvořena nová položka.
        /// </summary>
        public static string RozuctovatPopis {
            get {
                return ResourceManager.GetString("RozuctovatPopis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schvalovatel.
        /// </summary>
        public static string Schalovatel {
            get {
                return ResourceManager.GetString("Schalovatel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typ investice.
        /// </summary>
        public static string TypInvestice {
            get {
                return ResourceManager.GetString("TypInvestice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ukončit.
        /// </summary>
        public static string Ukoncit {
            get {
                return ResourceManager.GetString("Ukoncit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to uživatelem.
        /// </summary>
        public static string Uzivatelem {
            get {
                return ResourceManager.GetString("Uzivatelem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vybraný dodavatel.
        /// </summary>
        public static string VybrDodavatel {
            get {
                return ResourceManager.GetString("VybrDodavatel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Založil.
        /// </summary>
        public static string zalozil {
            get {
                return ResourceManager.GetString("zalozil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V zastoupení (jméno.příjmení).
        /// </summary>
        public static string zastoupeni {
            get {
                return ResourceManager.GetString("zastoupeni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zdůvodnění.
        /// </summary>
        public static string Zduvodneni {
            get {
                return ResourceManager.GetString("Zduvodneni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Způsob platby.
        /// </summary>
        public static string ZpusobPlatby {
            get {
                return ResourceManager.GetString("ZpusobPlatby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zvolte číslo investice ....
        /// </summary>
        public static string ZvolteCisloInvestice {
            get {
                return ResourceManager.GetString("ZvolteCisloInvestice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zvolte dodavatele ....
        /// </summary>
        public static string ZvolteDodavatele {
            get {
                return ResourceManager.GetString("ZvolteDodavatele", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zvolte číslo konta ....
        /// </summary>
        public static string ZvolteKonto {
            get {
                return ResourceManager.GetString("ZvolteKonto", resourceCulture);
            }
        }
    }
}
